[package]
name = "validator"
version = "0.1.0"
authors = ["Tristram Gräbener <tristramg@gmail.com>"]
edition = "2018"

[dependencies]
chrono = "0.4"
chrono-tz = "0.5"
env_logger = "0.6"
failure = "0.1"
failure_derive = "0.1"
futures = "0.1"
geo = "0.12"
gtfs-structures = "^0.11.3"
iso4217 = "0.3"
isolang = "1.0.0"
itertools = "0.8"
log = "0.4"
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"
structopt = "0.2"
structopt-derive = "0.2"
url = "1.7"
actix-web = "1.0.0-beta.2"
